import * as Enums from "@/enums"

let id = 0

const homeworkMockData = [
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.A,
    status: Enums.HomeworkStatus.Pending,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.B,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
  {
    id: id++,
    isDone: false,
    lesson: Enums.LessonsCode.Math,
    priority: Enums.HomeworkPriority.C,
    status: Enums.HomeworkStatus.Cancelled,
    description: "تمرینات صفحات ۵۶ تا ۷۵ در دفتر و با ==خودکار== حل شده و فیلم گرفته شود",
  },
  {
    id: id++,
    isDone: true,
    lesson: Enums.LessonsCode.Physics,
    priority: Enums.HomeworkPriority.D,
    status: Enums.HomeworkStatus.Done,
    description: "انجام آزمایش صفحه ۵۵۶ و ارسال نتیجه به صورت فیلم به ایمیل استاد",
  },
]

export default homeworkMockData
